# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-19 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='images/original')),
                ('status', models.CharField(max_length=25)),
                ('converted_image', models.ImageField(upload_to='images/resized')),
                ('converted_datetime', models.DateTimeField()),
                ('job_id', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
