# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=b'/home/katerina/test/resizer/media/images/original')),
                ('converted_image', models.ImageField(upload_to=b'/home/katerina/test/resizer/media/images/converted')),
                ('converted_datetime', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=25)),
                ('job_id', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('issues', models.TextField(null=True)),
            ],
        ),
    ]
