# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-19 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='converted_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
