# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20161119_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='converted_image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.CharField(max_length=100),
        ),
    ]
