# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-20 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20161120_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='job_id',
            field=models.CharField(max_length=100),
        ),
    ]
