# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20161120_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='issues',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='converted_image',
            field=models.ImageField(upload_to='media/images/original'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(upload_to='media/images/original'),
        ),
    ]
